spring:
  profiles:
    active: dev
  properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: src/main/resources/db/migration/h2/db_creation_mysql.sql

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:file:./db/markoth;MODE=MySQL;
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: true
  flyway:
    url: jdbc:h2:file:./db/markoth
    user: sa
    password:
    baseline-on-migrate: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/markoth?autoreconnect=true
    username: markothuser
    password: MUpassword
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: false
    show-sql: true
  flyway:
    url: jdbc:mysql://localhost:3306/markoth
    schemas: markoth
    user: "markothadmin"
    password: "MApassword"