DROP DATABASE IF EXISTS markoth;
DROP USER IF EXISTS `markothadmin`@`%`;
DROP USER IF EXISTS `markothuser`@`%`;
CREATE DATABASE IF NOT EXISTS markoth CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `markothadmin`@`%` IDENTIFIED WITH mysql_native_password BY 'MApassword';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `markoth`.* TO `markothadmin`@`%`;
CREATE USER IF NOT EXISTS `markothuser`@`%` IDENTIFIED WITH mysql_native_password BY 'MUpassword';
GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON `markoth`.* TO `markothuser`@`%`;
FLUSH PRIVILEGES;